eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
server:
  port: 8080
spring:
  application:
    name: app-portal-web
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path:
      - classpath:/templates
