eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
server:
  port: 8079
spring:
  application:
    name: app-portal-pay-web
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path:
      - classpath:/templates
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
xxl:
  sso:
    logout:
      path: /logout
    server: http://taodong.ssoserver.com:8099
xxl-sso:
  excluded:
    paths: '/test-xxl1,/test-xxl2'