eureka:
  client:
    service-url:
      defaultZone: http://192.168.162.135:8080/eureka
server:
  port: 80
spring:
  application:
    name: taodong-shop-basics-zuul
taodong-shop:
  zuul:
    swagger:
      document: '[ { "name": "taodong-shop-service-member", "location": "/taodong-shop-service-member/v2/api-docs",
                "version": "2.0" }, { "name": "taodong-shop-service-weixin", "location":
                "/taodong-shop-service-weixin/v2/api-docs", "version": "2.0" } ]'
