eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka
server:
  port: 8099

spring:
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  application:
    name: taodong-shop-basics-xxlsso-server
xxl:
  sso:
    redis:
      address: redis://127.0.0.1:6379
      expire:
        minute: 1440
